[project]
name = "nostr-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.9.0",
    "flask>=3.1.2",
    "flask-cors>=4.0.0",
    "gunicorn>=23.0.0",
    "mcp[cli]>=1.10.1",
    "pynostr>=0.7.0",
]

